---
version: "2"

linters:
  default: standard

  enable:
    - gocyclo
    - revive
    - goconst
    - unparam
    - gocritic

  settings:
    gocyclo:
      min-complexity: 10

    revive:
      rules:
        - name: blank-imports
        - name: errorf

    gocritic:
      enabled-checks:
        - dupImport
        - emptyStringTest